# Azure Pipeline settings
# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines

jobs:
- job: ubuntu_xenial_gcc_debug
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Debug
    BUILD_DIR: $(Build.SourcesDirectory)
    SUDO: sudo
  steps:
  - template: .ci/azure-pipelines/native.yml

- job: ubuntu_bionic_gcc_release
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    OS_NAME: linux
    COMPILER: gcc
    BUILD_TYPE: Release
    BUILD_DIR: $(Build.SourcesDirectory)
    DOCKERFILE: Dockerfile.ubuntu-bionic
  steps:
  - template: .ci/azure-pipelines/docker.yml
